server:
  port: 443

spring:
  cloud:
    gateway:
      # Filtro que elimina el primer segmento de la URL
      default-filters:
        - RewritePath=^/.*?/(?<remaining>.*)$, /${remaining}
      
      # AQUÍ EL CAMBIO NUEVO: Usando la estructura moderna recomendada por el log
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

springdoc:
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: stock-service
        url: /stock-service/v3/api-docs