server:
  port: 443

spring:
  cloud:
    gateway:
      # 1. Definimos rutas explícitas para el negocio y para Swagger
      routes:
        # --- RUTAS PARA SWAGGER (Mantiene la ruta limpia hacia el microservicio) ---
        - id: auth-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
            
        - id: product-swagger
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs

        # --- RUTAS NORMALES DE TU NEGOCIO (Usan tu filtro de reescritura) ---
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth-service/**
          filters:
            - name: RewritePath
              args:
                regexp: '^/.*?/.*?/(?<remaining>.*)$'
                replacement: '/${remaining}'

      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

# 2. Configuración de la interfaz gráfica de Swagger en el Gateway
springdoc:
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: stock-service
        url: /stock-service/v3/api-docs  