server:
  port: 443

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            # --- SWAGGER ---
            - id: auth-swagger
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/v3/api-docs/**
              filters:
                - StripPrefix=1

            - id: product-swagger
              uri: lb://product-service
              predicates:
                - Path=/product-service/v3/api-docs/**
              filters:
                - StripPrefix=1

            - id: stock-swagger
              uri: lb://stock-service
              predicates:
                - Path=/stock-service/v3/api-docs/**
              filters:
                - StripPrefix=1

            # --- NEGOCIO ---
            - id: auth-service-api
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth-service/**
              filters:
                - name: RewritePath
                  args:
                    regexp: '^/.*?/.*?/(?<remaining>.*)$'
                    replacement: '/${remaining}'

springdoc:
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: stock-service
        url: /stock-service/v3/api-docs